FROM alpine:latest as builder

WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add bash && \
    apk add openjdk11 && \
    apk add maven && \
    apk add git && \
    git clone https://github.com/rodrigospimentacwb/default-spring-test.git && \
    cd default-spring-test && \
    mvn clean install
